\workflows:
  android-apk-workflow:
    name: Android APK Generator
    max_build_duration: 30
    instance_type: mac_mini_m2
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'main'
          include: true
    scripts:
      - name: Generate missing gradle wrapper
        script: |
          gradle wrapper
      - name: Set Android SDK location
        script: | 
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
      - name: Grant execute permission to Gradle
        script: |
          chmod +x gradlew
      - name: Build Android APK
        script: |
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/apk/**/*.apk
    publishing:
      email:
        recipients:
          - smg00477@gmail.com
        notify:
          success: true
          failure: true
